// <auto-generated />
namespace PoliciesApp.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Updating_Relation_Between_Customers_And_Policies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updating_Relation_Between_Customers_And_Policies));
        
        string IMigrationMetadata.Id
        {
            get { return "201907032329051_Updating_Relation_Between_Customers_And_Policies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
